#!/usr/bin/env python3
"""6月下半月流动性风险报告生成器"""
import json, os

DATA_FILE = os.path.join(os.path.dirname(__file__), '..', 'data', 'portfolio.json')

def load():
    with open(DATA_FILE) as f:
        return json.load(f)

def generate():
    data = load()
    liq = data.get('liquidity', {})
    
    lines = []
    lines.append("🔴 6月下半月全球流动性风险预判")
    lines.append("🧸 Labuster 独立分析 · 2026-06-09")
    lines.append("")
    lines.append("━━━━━━━━━━━━━━━━━━━━")
    lines.append("")
    lines.append("📅 关键事件时间线")
    lines.append("")
    lines.append("  🔴 6/12 (本周五) — SpaceX 史上最大IPO路演")
    lines.append("       募资$750亿，$1.75万亿市值")
    lines.append("       散户配额30%创新高·21家投行联合承销")
    lines.append("  🔴 6/12 (同日) — 沪深300等指数调仓生效")
    lines.append("       超1200亿被动资金调仓换股")
    lines.append("  🔴 6/16 (下周二) — 日本央行利率决议")
    lines.append("       加息25bp至1%概率88%")
    lines.append("       日本已动用$740亿干预汇市")
    lines.append("  🔴 6月中旬 — 美联储沃什国会听证")
    lines.append("       缩表路线图可能首次披露")
    lines.append("  🔴 6月下旬 — 公募基金半年度考核调仓")
    lines.append("       机构从高位AI切换到防御板块")
    lines.append("  🔴 6月下旬 — 南向资金半年度结算")
    lines.append("       5月已出现单月净流出（35.5亿港元）")
    lines.append("  ⚠️ 持续 — 中东局势（霍尔木兹海峡封锁3月+）")
    lines.append("")

    # US section
    us = liq.get('US', {})
    lines.append("━━━━━━━━━━━━━━━━━━━━")
    lines.append(f"🇺🇸 美股 | {us.get('score',41)}/100 🔻 中性偏紧→偏危险")
    lines.append("")
    lines.append("三大流动性压力源即将叠加冲击：")
    lines.append("")
    lines.append("压力① 超级IPO资金冻结")
    lines.append("  · SpaceX 6/12路演，需$750亿认购资金")
    lines.append("  · Cerebras(已上市$950亿)+Databricks排队")
    lines.append("  · 合计$2000-3000亿资金需求")
    lines.append("  · 分析师警告：基金需从7巨头抽资")
    lines.append("")
    lines.append("压力② 日本加息引爆套息平仓")
    lines.append("  · 6/16 BOJ加息至1%概率88%")
    lines.append("  · 日元套息交易规模约$1-2万亿")
    lines.append("  · 平仓→风险资产全面波动")
    lines.append("  · 6/6日韩股市已大跌（韩国熔断）")
    lines.append("")
    lines.append("压力③ 科技巨头自身抽水")
    lines.append("  · GOOG：发$1750亿债 + 再融$800亿股权")
    lines.append("  · META：债务从$360亿爆到$840亿")
    lines.append("  · 5巨头合计Capex $7150亿+")
    lines.append("  · 回购能力被AI支出吞噬 → 股价支撑减弱")
    lines.append("")
    lines.append("🧸 判断：美股6月下半月波动率大概率上升")
    lines.append("  · SpaceX IPO当日→资金从科技7巨头抽离")
    lines.append("  · 日本加息次日→套息平仓二次冲击")
    lines.append("  · 7巨头中持仓最影响：NVDA/META/GOOG/AMZN")
    lines.append("  · 保护策略：Put持仓继续持有，不加仓7巨头")
    lines.append("  · 如果标普500回调>5%，反而是加仓机会")
    lines.append("")
    lines.append("关注指标：SOFR是否跳升，VIX>25触发预警")
    lines.append("")

    # HK section
    hk = liq.get('HK', {})
    lines.append("━━━━━━━━━━━━━━━━━━━━")
    lines.append(f"🇭🇰 港股 | {hk.get('score',55)}/100 → 中性偏松但有隐忧")
    lines.append("")
    lines.append("双重压力：")
    lines.append("")
    lines.append("压力① 港元流动性已处低位")
    lines.append("  · 金管局总结余仅537亿港元（历史低位）")
    lines.append("  · 港元在7.83-7.85弱方徘徊")
    lines.append("  · 若美联储推迟降息→港元再触弱方→金管局被动收紧")
    lines.append("")
    lines.append("压力② 南向资金面临半年度衰减")
    lines.append("  · 5月已首次单月净流出（35.5亿）")
    lines.append("  · 6月末基金考核→可能继续收缩")
    lines.append("  · 但今年累计仍+2800亿，趋势未破")
    lines.append("")
    lines.append("🧸 判断：港股受美股波动传导，但南向资金仍然提供底线支撑")
    lines.append("  · 腾讯0700：底部支撑较稳（自营资金+回购）")
    lines.append("  · 阿里9988：季度业绩疲软，但AI+云计算增长")
    lines.append("  · 群核科技0068：次新股，波动大，仓位轻无需担心")
    lines.append("")

    # A section
    a = liq.get('A', {})
    lines.append("━━━━━━━━━━━━━━━━━━━━")
    lines.append(f"🇨🇳 A股 | {a.get('score',60)}/100 → 相对最稳")
    lines.append("")
    lines.append("A股是三大市场中受外部冲击影响最小的：")
    lines.append("")
    lines.append("利好因素：")
    lines.append("  · 央行持续投放（MLF 6000亿+逆回购5000亿）")
    lines.append("  · 北向资金持仓突破4万亿，长期增配趋势明确")
    lines.append("  · 十年国债1.70%低位，资产荒格局延续")
    lines.append("  · 科创再贷款从8000亿→1.2万亿，定向宽松")
    lines.append("")
    lines.append("利空因素：")
    lines.append("  · PPI快速上冲（4月2.8%，5-6月或达4-5%）")
    lines.append("  · 央行开始回笼超宽松预期，关注资金空转")
    lines.append("  · 半年度基金调仓→高位AI板块承压")
    lines.append("  · 外部情绪传导（日本加息/中东）")
    lines.append("")
    lines.append("🧸 判断：A股以我为主，流动性继续保持中性偏松")
    lines.append("  · A500 ETF：定投策略继续，无需因外部波动调整")
    lines.append("  · 红利低波ETF：防御配置，半年度调仓期反而受益")
    lines.append("")

    # Cross-market synthesis
    lines.append("━━━━━━━━━━━━━━━━━━━━")
    lines.append("📊 跨市场风险传导链推演")
    lines.append("")
    lines.append("  情景A（基准概率60%）：局部波动，消化后反弹")
    lines.append("    SpaceX上市顺利→市场消化$750亿→VIX短暂上冲→")
    lines.append("    日本加息25bp落地→套息平仓2-3天→市场恢复")
    lines.append("    影响：美股-3~5%调整，港股-2~3%，A股-1~2%")
    lines.append("")
    lines.append("  情景B（概率25%）：事件叠加，较大调整")
    lines.append("    SpaceX认购不足→科技股资金大量流出→")
    lines.append("    同日日本加息→套息踩踏→7巨头跌5-10%→")
    lines.append("    港股南向资金流出→恒指跌破22000")
    lines.append("    影响：美股-8~12%，港股-5~8%，A股-3~5%")
    lines.append("")
    lines.append("  情景C（概率15%）：流动性危机（小概率但需预防）")
    lines.append("    中东局势突然升级+RPP耗尽+QT加速→")
    lines.append("    回购市场利率飙升→2019危机重演→")
    lines.append("    美联储紧急介入")
    lines.append("")

    lines.append("━━━━━━━━━━━━━━━━━━━━")
    lines.append("🎯 持仓应对建议")
    lines.append("")
    lines.append("现有保护措施：")
    lines.append("  ✅ NVDA Put $195 6/26 — 持有，保护AI核心仓位")
    lines.append("  ✅ AMZN Put $245 6/18 — 持有，下周到期前关注")
    lines.append("  ✅ 阿里 Put HK$115 6/29 — 持有，港股保护")
    lines.append("")
    lines.append("建议动作：")
    lines.append("  · SPY已清仓，无需额外对冲")
    lines.append("  · 货基8.3万美元+HKD 50万可作为弹药")
    lines.append("  · 如果情景A出现（美股-5%），考虑逐步加仓NVDA/MSFT")
    lines.append("  · INTU已半仓（50股@$301.50），观察Q4季节性反弹")
    lines.append("")
    lines.append("最需要关注的日期：")
    lines.append("  🔴 6/12-6/16（SpaceX+BOJ连续冲击）")
    lines.append("  🔴 6/18（AMZN Put到期日）")
    lines.append("  🔴 6/26（NVDA Put + INTU Put到期日）")
    lines.append("  🔴 6/29（阿里Put到期日）")
    lines.append("")

    lines.append("━━━━━━━━━━━━━━━━━━━━")
    lines.append("🧸 Labuster · 非投资建议 · 数据来源网络")
    lines.append("📌 本报告基于流动性框架实时评估，")
    lines.append("    如有重大事件将推送更新")

    return '\n'.join(lines)

if __name__ == '__main__':
    print(generate())
